# Setup
title:               Max Laponsky
tagline:             'Data scientist with a passion for NLP, basketball and music.'
description:         'A blog for all of my personal projects, from music-based NLP projects to basketball analytics -- to wherever my latest obsession takes me.'
url:                 https://mlaponsky.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Max Laponsky
  url:               http://github.com/mlaponsky
  email:             thebiglaponsky@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
